# The URL the site will be built for
theme = "tabi"
base_url = "https://mukund-yedunuthala.de"
title = "Venkata Mukund Kashyap Yedunuthala"
description = "A portfolio site that contains all the information about Venkata Mukund Kashyap Yedunuthala."
compile_sass = true
minify_html = true
default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[link_checker]
internal_level = "warn"

[languages.de]
title = "Venkata Mukund Kashyap Yedunuthala"
description = "Portfolio Webseite"



[extra]
language_name.en = "English"
language_name.de = "Deutsch"
base_canonical_url = "https://mukund-yedunuthala.de"
social_media_card = "img/me.jpg"

theme_switcher = true
default_theme = "dark"
skin = "lavender"
favicon_emoji = "⚛️"
headerImage = "img/me.jpg"


remote_repository_url = "https://git.mukund-yedunuthala.de/mukund-yedunuthala/portfolio-zola-tabi"
remote_repository_git_platform = "auto"
remote_repository_branch = "master"
show_remote_changes = true
show_remote_source = true

copy_button = true
show_reading_time = false
footnote_backlinks = false
katex = false
quick_navigation_buttons = true
toc = false
long_date_format = "%d %B %Y"
invert_title_order = true

menu = [
    { name = "About", url = "about", trailing_slash = true },
    { name = "Projects", url = "projects", trailing_slash = true },
]
footer_menu = [
    {url = "imprint", name = "Imprint", trailing_slash = true},
    {url = "privacy-policy", name = "Privacy policy", trailing_slash = true},
    {url = "sitemap.xml", name = "Sitemap", trailing_slash = false},
]
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]


email="bXVrdW5kLnllZHVudXRoYWxhQG91dGxvb2suZGU="
socials = [
    { name = "Gitlab", url = "https://gitlab.com/mukund-yedunuthala/", icon = "gitlab" },
    { name = "Forgejo", url = "https://git.mukund-yedunuthala.de/mukund-yedunuthala/", icon = "forgejo"},
    { name = "Firefish", url = "https://fedia.social/@mukskashyap", icon = "firefish" },
    { name = "Pixelfed", url = "https://pixelfed.social/@mukskashyap", icon = "pixelfed" },

]
copyright = "Copyright © $CURRENT_YEAR Venkata Mukund Kashyap Yedunuthala $SEPARATOR Unless otherwise noted, the content in this website is available under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license."
translate_copyright = true